// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Adjustment extends Equatable {
  final String id;
  final String stockId;
  final int quantityChange;
  final String reason;
  final String performedByUserId;
  final DateTime timestamp;

  const Adjustment({
    required this.id,
    required this.stockId,
    required this.quantityChange,
    required this.reason,
    required this.performedByUserId,
    required this.timestamp,
  });

  Adjustment copyWith({
    String? id,
    String? stockId,
    int? quantityChange,
    String? reason,
    String? performedByUserId,
    DateTime? timestamp,
  }) {
    return Adjustment(
      id: id ?? this.id,
      stockId: stockId ?? this.stockId,
      quantityChange: quantityChange ?? this.quantityChange,
      reason: reason ?? this.reason,
      performedByUserId: performedByUserId ?? this.performedByUserId,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  @override
  List<Object?> get props => [
    id,
    stockId,
    quantityChange,
    reason,
    performedByUserId,
    timestamp,
  ];
}
