// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

enum StockTakeStatus {
  active,
  completed,
  cancelled,
  paused,
}

class StockTake extends Equatable {
  final String id;
  final String name;
  final String? description;
  final DateTime startDate;
  final DateTime? endDate;
  final StockTakeStatus status;
  final String createdBy;
  final List<String> assignedTo;
  final String? locationId;
  final List<String>? categoryFilters;
  final int totalItems;
  final int countedItems;
  final int discrepancies;
  final Map<String, dynamic>? metadata;
  final DateTime createdAt;
  final DateTime updatedAt;

  const StockTake({
    required this.id,
    required this.name,
    this.description,
    required this.startDate,
    this.endDate,
    required this.status,
    required this.createdBy,
    required this.assignedTo,
    this.locationId,
    this.categoryFilters,
    required this.totalItems,
    required this.countedItems,
    required this.discrepancies,
    this.metadata,
    required this.createdAt,
    required this.updatedAt,
  });

  StockTake copyWith({
    String? id,
    String? name,
    String? description,
    DateTime? startDate,
    DateTime? endDate,
    StockTakeStatus? status,
    String? createdBy,
    List<String>? assignedTo,
    String? locationId,
    List<String>? categoryFilters,
    int? totalItems,
    int? countedItems,
    int? discrepancies,
    Map<String, dynamic>? metadata,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return StockTake(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      status: status ?? this.status,
      createdBy: createdBy ?? this.createdBy,
      assignedTo: assignedTo ?? this.assignedTo,
      locationId: locationId ?? this.locationId,
      categoryFilters: categoryFilters ?? this.categoryFilters,
      totalItems: totalItems ?? this.totalItems,
      countedItems: countedItems ?? this.countedItems,
      discrepancies: discrepancies ?? this.discrepancies,
      metadata: metadata ?? this.metadata,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        name,
        description,
        startDate,
        endDate,
        status,
        createdBy,
        assignedTo,
        locationId,
        categoryFilters,
        totalItems,
        countedItems,
        discrepancies,
        metadata,
        createdAt,
        updatedAt,
      ];
}
