// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

enum MovementType {
  INBOUND, // Stock added to inventory
  OUTBOUND, // Stock removed from inventory
  TRANSFER, // Stock moved between locations
  ADJUSTMENT, // Manual adjustment of stock levels
}

class StockMovement extends Equatable {
  final String id;
  final String stockId;
  final MovementType type;
  final int quantity;
  final String? reason;
  final String? referenceId;
  final String? performedByUserId;
  final String? fromLocation;
  final String? toLocation;
  final DateTime timestamp;

  const StockMovement({
    required this.id,
    required this.stockId,
    required this.type,
    required this.quantity,
    this.reason,
    this.referenceId,
    this.performedByUserId,
    this.fromLocation,
    this.toLocation,
    required this.timestamp,
  });

  StockMovement copyWith({
    String? id,
    String? stockId,
    MovementType? type,
    int? quantity,
    String? reason,
    String? referenceId,
    String? performedByUserId,
    String? fromLocation,
    String? toLocation,
    DateTime? timestamp,
  }) {
    return StockMovement(
      id: id ?? this.id,
      stockId: stockId ?? this.stockId,
      type: type ?? this.type,
      quantity: quantity ?? this.quantity,
      reason: reason ?? this.reason,
      referenceId: referenceId ?? this.referenceId,
      performedByUserId: performedByUserId ?? this.performedByUserId,
      fromLocation: fromLocation ?? this.fromLocation,
      toLocation: toLocation ?? this.toLocation,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  @override
  List<Object?> get props => [
    id,
    stockId,
    type,
    quantity,
    reason,
    referenceId,
    performedByUserId,
    fromLocation,
    toLocation,
    timestamp,
  ];
}
