// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class StockBatch extends Equatable {
  final String batchId;
  final String stockId;
  final int quantity;
  final DateTime manufactureDate;
  final DateTime? expiryDate;

  const StockBatch({
    required this.batchId,
    required this.stockId,
    required this.quantity,
    required this.manufactureDate,
    this.expiryDate,
  });

  StockBatch copyWith(
      {String? batchId, String? stockId, int? quantity, DateTime? manufactureDate, DateTime?? expiryDate}) {
    return StockBatch(
      batchId: batchId ?? this.batchId,
      stockId: stockId ?? this.stockId,
      quantity: quantity ?? this.quantity,
      manufactureDate: manufactureDate ?? this.manufactureDate,
      expiryDate: expiryDate ?? this.expiryDate,
    );
  }

  @override
  List<Object?> get props =>
      [batchId, stockId, quantity, manufactureDate, expiryDate];
}
