// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Stock extends Equatable {


  const Stock

  (

  {

});

Stock copyWith
(
{}) {
return Stock(

);
}

@override
List<Object?> get props => [];
}
