// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/domain/entities/reporting/expiry_report.dart';

import '../../models/reporting/expiry_report_model.dart';

class ExpiryReportMapper {
  static ExpiryReport toEntity(ExpiryReportModel model) {
    return ExpiryReport(
      stockId: model.stockId,
      name: model.name,
      expiryDate: model.expiryDate,
      daysToExpiry: model.daysToExpiry,
      quantity: model.quantity,
    );
  }

  static ExpiryReportModel fromEntity(ExpiryReport entity) {
    return ExpiryReportModel(
      stockId: entity.stockId,
      name: entity.name,
      expiryDate: entity.expiryDate,
      daysToExpiry: entity.daysToExpiry,
      quantity: entity.quantity,
    );
  }
}
