// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/models/reporting/reorder_report_model.dart';
import 'package:clean_arch_app/domain/entities/reporting/reorder_report.dart';

class ReorderReportMapper {
  static ReorderReport toEntity(ReorderReportModel model) {
    return ReorderReport(
      stockId: model.stockId,
      name: model.name,
      quantity: model.quantity,
      minimumStock: model.minimumStock,
      needsReorder: model.needsReorder,
    );
  }

  static ReorderReportModel fromEntity(ReorderReport entity) {
    return ReorderReportModel(
      stockId: entity.stockId,
      name: entity.name,
      quantity: entity.quantity,
      minimumStock: entity.minimumStock,
      needsReorder: entity.needsReorder,
    );
  }
}
