// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/stockMovementReportModel.dart';
import 'package:clean_arch_app/domain/entities/stockMovementReport.dart';

class StockMovementReportMapper {
  static StockMovementReport toEntity(StockMovementReportModel model) {
    return StockMovementReport(
      movementId: model.movementId,
      stockId: model.stockId,
      type: model.type,
      quantity: model.quantity,
      performedBy: model.performedBy,
      timestamp: model.timestamp,
      reason: model.reason,
    );
  }

  static StockMovementReportModel fromEntity(StockMovementReport entity) {
    return StockMovementReportModel(
      movementId: entity.movementId,
      stockId: entity.stockId,
      type: entity.type,
      quantity: entity.quantity,
      performedBy: entity.performedBy,
      timestamp: entity.timestamp,
      reason: entity.reason,
    );
  }
}
