// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/general//location.dart';

part '../settings/location_model.g.dart';

@JsonSerializable()
class LocationModel extends Equatable {
  final String id;
  final String name;
  final String? description;
  final double? latitude;
  final double? longitude;

  const LocationModel({
    required this.id,
    required this.name,
    this.description,
    this.latitude,
    this.longitude,
  });

  factory LocationModel.fromJson(Map<String, dynamic> json) =>
      _$LocationModelFromJson(json);

  Map<String, dynamic> toJson() => _$LocationModelToJson(this);

  Location toDomain() => Location(
    id: id,
    name: name,
    description: description,
    latitude: latitude,
    longitude: longitude,
  );

  static LocationModel fromDomain(Location ent) => LocationModel(
    id: ent.id,
    name: ent.name,
    description: ent.description,
    latitude: ent.latitude,
    longitude: ent.longitude,
  );

  LocationModel copyWith({
    String? id,
    String? name,
    String? description,
    double? latitude,
    double? longitude,
  }) {
    return LocationModel(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
    );
  }

  @override
  List<Object?> get props => [id, name, description, latitude, longitude];
}
