// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/general/notification.dart';

part '../settings/notification_model.g.dart';

@JsonSerializable()
class NotificationModel extends Equatable {
  final String id;
  final String userId;
  final String title;
  final String message;
  final bool read;
  final DateTime createdAt;

  const NotificationModel({
    required this.id,
    required this.userId,
    required this.title,
    required this.message,
    this.read = false,
    required this.createdAt,
  });

  factory NotificationModel.fromJson(Map<String, dynamic> json) =>
      _$NotificationModelFromJson(json);

  Map<String, dynamic> toJson() => _$NotificationModelToJson(this);

  Notification toDomain() => Notification(
    id: id,
    userId: userId,
    title: title,
    message: message,
    read: read,
    createdAt: createdAt,
  );

  static NotificationModel fromDomain(Notification ent) => NotificationModel(
    id: ent.id,
    userId: ent.userId,
    title: ent.title,
    message: ent.message,
    read: ent.read,
    createdAt: ent.createdAt,
  );

  NotificationModel copyWith({
    String? id,
    String? userId,
    String? title,
    String? message,
    bool? read,
    DateTime? createdAt,
  }) {
    return NotificationModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      message: message ?? this.message,
      read: read ?? this.read,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  List<Object?> get props => [id, userId, title, message, read, createdAt];
}
