// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/general/unit.dart';

part '../settings/unit_model.g.dart';

@JsonSerializable()
class UnitModel extends Equatable {
  final String id;
  final String name; // e.g. 'kg', 'pcs', 'litre'
  final String? description;
  final double? conversionRate; // relative to base unit

  const UnitModel({
    required this.id,
    required this.name,
    this.description,
    this.conversionRate,
  });

  factory UnitModel.fromJson(Map<String, dynamic> json) =>
      _$UnitModelFromJson(json);

  Map<String, dynamic> toJson() => _$UnitModelToJson(this);

  Unit toDomain() => Unit(
    id: id,
    name: name,
    description: description,
    conversionRate: conversionRate,
  );

  static UnitModel fromDomain(Unit ent) => UnitModel(
    id: ent.id,
    name: ent.name,
    description: ent.description,
    conversionRate: ent.conversionRate,
  );

  UnitModel copyWith({
    String? id,
    String? name,
    String? description,
    double? conversionRate,
  }) {
    return UnitModel(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      conversionRate: conversionRate ?? this.conversionRate,
    );
  }

  @override
  List<Object?> get props => [id, name, description, conversionRate];
}
