// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/mappers/catalog/bom_item_mapper.dart';
import 'package:clean_arch_app/data/models/catalog/bill_of_material_model.dart';
import 'package:clean_arch_app/domain/entities/catalog/bill_of_material.dart';

class BillOfMaterialsMapper {
  static BillOfMaterials toEntity(BillOfMaterialsModel model) {
    return BillOfMaterials(
      productId: model.productId,
      components: model.components
          .map((e) => BomItemMapper.toEntity(e))
          .toList(),
      yieldPerRun: model.yieldPerRun,
      scrapPercent: model.scrapPercent,
    );
  }

  static BillOfMaterialsModel fromEntity(BillOfMaterials entity) {
    return BillOfMaterialsModel(
      productId: entity.productId,
      components: entity.components
          .map((e) => BomItemMapper.fromEntity(e))
          .toList(),
      yieldPerRun: entity.yieldPerRun,
      scrapPercent: entity.scrapPercent,
    );
  }
}
