// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/bomItemModel.dart';
import 'package:clean_arch_app/domain/entities/bomItem.dart';

class BomItemMapper {
  static BomItem toEntity(BomItemModel model) {
    return BomItem(
      rawMaterialId: model.rawMaterialId,
      quantityPerUnit: model.quantityPerUnit,
    );
  }

  static BomItemModel fromEntity(BomItem entity) {
    return BomItemModel(
      rawMaterialId: entity.rawMaterialId,
      quantityPerUnit: entity.quantityPerUnit,
    );
  }
}
