// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/categoryModel.dart';
import 'package:clean_arch_app/domain/entities/category.dart';

class CategoryMapper {
  static Category toEntity(CategoryModel model) {
    return Category(
      id: model.id,
      name: model.name,
      description: model.description,
      parentCategoryId: model.parentCategoryId,
    );
  }

  static CategoryModel fromEntity(Category entity) {
    return CategoryModel(
      id: entity.id,
      name: entity.name,
      description: entity.description,
      parentCategoryId: entity.parentCategoryId,
    );
  }
}
