// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/productModel.dart';
import 'package:clean_arch_app/domain/entities/product.dart';

class ProductMapper {
  static Product toEntity(ProductModel model) {
    return Product(
        id: model.id,
        name: model.name,
        sku: model.sku,
        description: model.description,
        categoryId: model.categoryId,
        supplierId: model.supplierId,
        price: model.price,
        costPrice: model.costPrice,
        tags: model.tags?.map((e) => String Mapper.toEntity(e)).toList(),);
  }

  static ProductModel fromEntity(Product entity) {
    return ProductModel(
        id: entity.id,
        name: entity.name,
        sku: entity.sku,
        description: entity.description,
        categoryId: entity.categoryId,
        supplierId: entity.supplierId,
        price: entity.price,
        costPrice: entity.costPrice,
        tags: entity.tags?.map((e) => String Mapper.fromEntity(e)).toList(),);
  }
}
