// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:stocktrack_pro/data/models/catalog/supplier_model.dart';
import 'package:stocktrack_pro/domain/entities/catalog/supplier.dart';

class SupplierMapper {
  static Supplier toEntity(SupplierModel model) {
    return Supplier(
      id: model.id,
      name: model.name,
    );
  }

  static SupplierModel fromEntity(Supplier entity) {
    return SupplierModel(
      id: entity.id,
      name: entity.name,
    );
  }
}
