// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:stocktrack_pro/data/models/catalog/supplier_model.dart';
import 'package:stocktrack_pro/domain/entities/catalog/supplier.dart';

class SupplierMapper {
  static Supplier toEntity(SupplierModel model) {
    return Supplier(
      id: model.id,
      name: model.name,
      contactInfo: model.contactInfo,
      rating: model.rating,
      paymentTerms: model.paymentTerms,
      isActive: model.isActive,
      address: model.address,
    );
  }

  static SupplierModel fromEntity(Supplier entity) {
    return SupplierModel(
      id: entity.id,
      name: entity.name,
      contactInfo: entity.contactInfo,
      rating: entity.rating,
      paymentTerms: entity.paymentTerms,
      isActive: entity.isActive,
      address: entity.address,
    );
  }
}
