// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/supplierModel.dart';
import 'package:clean_arch_app/domain/entities/supplier.dart';

class SupplierMapper {
  static Supplier toEntity(SupplierModel model) {
    return Supplier(id: model.id, name: model.name);
  }

  static SupplierModel fromEntity(Supplier entity) {
    return SupplierModel(id: entity.id, name: entity.name);
  }
}
