// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Customer extends Equatable {
  final String id;
  final String name;
  final String? email;
  final String? phone;
  final String? loyaltyId;

  const Customer({
    required this.id,
    required this.name,
    this.email,
    this.phone,
    this.loyaltyId,
  });

  Customer copyWith(
      {String? id, String? name, String?? email, String?? phone, String?? loyaltyId}) {
    return Customer(
      id: id ?? this.id,
      name: name ?? this.name,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      loyaltyId: loyaltyId ?? this.loyaltyId,
    );
  }

  @override
  List<Object?> get props => [id, name, email, phone, loyaltyId];
}
