// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/domain/entities/sales/sales_order_item.dart';
import 'package:equatable/equatable.dart';

class SalesOrder extends Equatable {
  final String id;
  final String customerId;
  final String createdByUserId;
  final DateTime createdAt;
  final String status;
  final List<SalesOrderItem> items;
  final double totalAmount;
  final String? notes;

  const SalesOrder({
    required this.id,
    required this.customerId,
    required this.createdByUserId,
    required this.createdAt,
    required this.status,
    required this.items,
    required this.totalAmount,
    this.notes,
  });

  SalesOrder copyWith(
      {String? id, String? customerId, String? createdByUserId, DateTime? createdAt, String? status, List<
          SalesOrderItem>? items, double? totalAmount, String? notes}) {
    return SalesOrder(
      id: id ?? this.id,
      customerId: customerId ?? this.customerId,
      createdByUserId: createdByUserId ?? this.createdByUserId,
      createdAt: createdAt ?? this.createdAt,
      status: status ?? this.status,
      items: items ?? this.items,
      totalAmount: totalAmount ?? this.totalAmount,
      notes: notes ?? this.notes,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        customerId,
        createdByUserId,
        createdAt,
        status,
        items,
        totalAmount,
        notes
      ];
}
