// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/domain/entities/sales/sales_order_item.dart';
import 'package:equatable/equatable.dart';

class SalesReturn extends Equatable {
  final String id;
  final String salesOrderId;
  final String returnedByUserId;
  final DateTime returnedAt;
  final List<SalesOrderItem> items;
  final double refundAmount;
  final String? reason;
  final String status;

  const SalesReturn({
    required this.id,
    required this.salesOrderId,
    required this.returnedByUserId,
    required this.returnedAt,
    required this.items,
    required this.refundAmount,
    this.reason,
    required this.status,
  });

  SalesReturn copyWith(
      {String? id, String? salesOrderId, String? returnedByUserId, DateTime? returnedAt, List<
          SalesOrderItem>? items, double? refundAmount, String? reason, String? status}) {
    return SalesReturn(
      id: id ?? this.id,
      salesOrderId: salesOrderId ?? this.salesOrderId,
      returnedByUserId: returnedByUserId ?? this.returnedByUserId,
      returnedAt: returnedAt ?? this.returnedAt,
      items: items ?? this.items,
      refundAmount: refundAmount ?? this.refundAmount,
      reason: reason ?? this.reason,
      status: status ?? this.status,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        salesOrderId,
        returnedByUserId,
        returnedAt,
        items,
        refundAmount,
        reason,
        status
      ];
}
