// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class SalesOrderItem extends Equatable {
  final String stockId;
  final int quantity;
  final double unitPrice;

  const SalesOrderItem({
    required this.stockId,
    required this.quantity,
    required this.unitPrice,
  });

  SalesOrderItem copyWith({String? stockId, int? quantity, double? unitPrice}) {
    return SalesOrderItem(
      stockId: stockId ?? this.stockId,
      quantity: quantity ?? this.quantity,
      unitPrice: unitPrice ?? this.unitPrice,
    );
  }

  @override
  List<Object?> get props => [stockId, quantity, unitPrice];
}
