// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/stock/adjustment_model.dart';
import 'package:stocktrack_pro/domain/entities/stock/adjustment.dart';

class AdjustmentMapper {
  static Adjustment toEntity(AdjustmentModel model) {
    return Adjustment(
      id: model.id,
      stockId: model.stockId,
      quantityChange: model.quantityChange,
      reason: model.reason,
      performedByUserId: model.performedByUserId,
      timestamp: model.timestamp,
    );
  }

  static AdjustmentModel fromEntity(Adjustment entity) {
    return AdjustmentModel(
      id: entity.id,
      stockId: entity.stockId,
      quantityChange: entity.quantityChange,
      reason: entity.reason,
      performedByUserId: entity.performedByUserId,
      timestamp: entity.timestamp,
    );
  }
}
