// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/adjustmentModel.dart';
import 'package:clean_arch_app/domain/entities/adjustment.dart';

class AdjustmentMapper {
  static Adjustment toEntity(AdjustmentModel model) {
    return Adjustment(
      id: model.id,
      stockId: model.stockId,
      quantityChange: model.quantityChange,
      reason: model.reason,
      performedByUserId: model.performedByUserId,
      timestamp: model.timestamp,
    );
  }

  static AdjustmentModel fromEntity(Adjustment entity) {
    return AdjustmentModel(
      id: entity.id,
      stockId: entity.stockId,
      quantityChange: entity.quantityChange,
      reason: entity.reason,
      performedByUserId: entity.performedByUserId,
      timestamp: entity.timestamp,
    );
  }
}
