// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:stocktrack_pro/data/models/stock/stock_movement_model.dart';
import 'package:stocktrack_pro/domain/entities/stock/stock_movement.dart';

class MovementTypeMapper {
  static MovementType toEntity(MovementTypeModel model) =>
      MovementType.values.byName(model.name);

  static MovementTypeModel fromEntity(MovementType entity) =>
      MovementTypeModel.values.byName(entity.name);

  static List<MovementType> toEntityList(List<MovementTypeModel> models) =>
      models.map(toEntity).toList();

  static List<MovementTypeModel> fromEntityList(List<MovementType> entities) =>
      entities.map(fromEntity).toList();
}
