// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/stock/stock_take_model.dart';
import 'package:clean_arch_app/domain/entities/stock/stock_take.dart';

class StockTakeMapper {
  static StockTake toEntity(StockTakeModel model) {
    return StockTake();
  }

  static StockTakeModel fromEntity(StockTake entity) {
    return StockTakeModel();
  }
}
