// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/stock/stock_batch_model.dart';
import 'package:stocktrack_pro/domain/entities/stock/stock_batch.dart';

class StockBatchMapper {
  static StockBatch toEntity(StockBatchModel model) {
    return StockBatch(
      batchId: model.batchId,
      stockId: model.stockId,
      quantity: model.quantity,
      manufactureDate: model.manufactureDate,
      expiryDate: model.expiryDate,
    );
  }

  static StockBatchModel fromEntity(StockBatch entity) {
    return StockBatchModel(
      batchId: entity.batchId,
      stockId: entity.stockId,
      quantity: entity.quantity,
      manufactureDate: entity.manufactureDate,
      expiryDate: entity.expiryDate,
    );
  }
}
