// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/stock/stock_model.dart';
import 'package:stocktrack_pro/domain/entities/stock/stock.dart';

class StockMapper {
  static Stock toEntity(StockModel model) {
    return model.toEntity();
  }

  static StockModel fromEntity(Stock entity) {
    return StockModel.fromDomain(entity);
  }
}
