// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/mappers/stock/movement_type_mappers.dart';
import 'package:clean_arch_app/data/models/stock/stock_movement_model.dart';
import 'package:clean_arch_app/domain/entities/stock/stock_movement.dart';

class StockMovementMapper {
  static StockMovement toEntity(StockMovementModel model) {
    return StockMovement(
      id: model.id,
      stockId: model.stockId,
      type: MovementTypeMapper.toEntity(model.type!),
      quantity: model.quantity,
      reason: model.reason,
      referenceId: model.referenceId,
      performedByUserId: model.performedByUserId,
      fromLocation: model.fromLocation,
      toLocation: model.toLocation,
      timestamp: model.timestamp,
    );
  }

  static StockMovementModel fromEntity(StockMovement entity) {
    return StockMovementModel(
      id: entity.id,
      stockId: entity.stockId,
      type: MovementTypeMapper.fromEntity(entity.type!),
      quantity: entity.quantity,
      reason: entity.reason,
      referenceId: entity.referenceId,
      performedByUserId: entity.performedByUserId,
      fromLocation: entity.fromLocation,
      toLocation: entity.toLocation,
      timestamp: entity.timestamp,
    );
  }
}
