// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/stockTakeModel.dart';
import 'package:clean_arch_app/domain/entities/stockTake.dart';

class StockTakeMapper {
  static StockTake toEntity(StockTakeModel model) {
    return StockTake();
  }

  static StockTakeModel fromEntity(StockTake entity) {
    return StockTakeModel();
  }
}
