// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/stockModel.dart';
import 'package:clean_arch_app/domain/entities/stock.dart';

class StockMapper {
  static Stock toEntity(StockModel model) {
    return Stock();
  }

  static StockModel fromEntity(Stock entity) {
    return StockModel();
  }
}
