// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/settings/export_import_settings.dart';

part 'export_import_settings_model.g.dart';

@JsonSerializable()
class ExportImportSettingsModel extends Equatable {
  final bool exportEnabled;
  final bool importEnabled;
  final Map<String, dynamic>? importValidationRules; // e.g. required columns

  const ExportImportSettingsModel({
    required this.exportEnabled,
    required this.importEnabled,
    this.importValidationRules,
  });

  factory ExportImportSettingsModel.fromJson(Map<String, dynamic> json) =>
      _$ExportImportSettingsModelFromJson(json);

  Map<String, dynamic> toJson() => _$ExportImportSettingsModelToJson(this);

  ExportImportSettings toDomain() => ExportImportSettings(
    exportEnabled: exportEnabled,
    importEnabled: importEnabled,
    importValidationRules: importValidationRules,
  );

  static ExportImportSettingsModel fromDomain(ExportImportSettings ent) =>
      ExportImportSettingsModel(
        exportEnabled: ent.exportEnabled,
        importEnabled: ent.importEnabled,
        importValidationRules: ent.importValidationRules,
      );

  ExportImportSettingsModel copyWith({
    bool? exportEnabled,
    bool? importEnabled,
    Map<String, dynamic>? importValidationRules,
  }) {
    return ExportImportSettingsModel(
      exportEnabled: exportEnabled ?? this.exportEnabled,
      importEnabled: importEnabled ?? this.importEnabled,
      importValidationRules:
          importValidationRules ?? this.importValidationRules,
    );
  }

  @override
  List<Object?> get props => [
    exportEnabled,
    importEnabled,
    importValidationRules,
  ];
}
