// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/settings/feature_toggle.dart';

part 'feature_toggle_model.g.dart';

@JsonSerializable()
class FeatureToggleModel extends Equatable {
  final String featureKey; // e.g. 'supplierSupport', 'exportImport'
  final bool enabled;
  final Map<String, dynamic>? config; // feature-specific settings

  const FeatureToggleModel({
    required this.featureKey,
    required this.enabled,
    this.config,
  });

  factory FeatureToggleModel.fromJson(Map<String, dynamic> json) =>
      _$FeatureToggleModelFromJson(json);

  Map<String, dynamic> toJson() => _$FeatureToggleModelToJson(this);

  FeatureToggle toDomain() =>
      FeatureToggle(featureKey: featureKey, enabled: enabled, config: config);

  static FeatureToggleModel fromDomain(FeatureToggle ent) => FeatureToggleModel(
    featureKey: ent.featureKey,
    enabled: ent.enabled,
    config: ent.config,
  );

  FeatureToggleModel copyWith({
    String? featureKey,
    bool? enabled,
    Map<String, dynamic>? config,
  }) {
    return FeatureToggleModel(
      featureKey: featureKey ?? this.featureKey,
      enabled: enabled ?? this.enabled,
      config: config ?? this.config,
    );
  }

  @override
  List<Object?> get props => [featureKey, enabled, config];
}
