// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/settings/supplier_support_settings.dart';

part 'supplier_support_settings_model.g.dart';

@JsonSerializable()
class SupplierSupportSettingsModel extends Equatable {
  final bool enabled;
  final List<String>? supplierRoles; // roles considered suppliers
  final Map<String, dynamic>? config; // e.g. approvalThreshold

  const SupplierSupportSettingsModel({
    required this.enabled,
    this.supplierRoles,
    this.config,
  });

  factory SupplierSupportSettingsModel.fromJson(Map<String, dynamic> json) =>
      _$SupplierSupportSettingsModelFromJson(json);

  Map<String, dynamic> toJson() => _$SupplierSupportSettingsModelToJson(this);

  SupplierSupportSettings toDomain() => SupplierSupportSettings(
    enabled: enabled,
    supplierRoles: supplierRoles,
    config: config,
  );

  static SupplierSupportSettingsModel fromDomain(SupplierSupportSettings ent) =>
      SupplierSupportSettingsModel(
        enabled: ent.enabled,
        supplierRoles: ent.supplierRoles,
        config: ent.config,
      );

  SupplierSupportSettingsModel copyWith({
    bool? enabled,
    List<String>? supplierRoles,
    Map<String, dynamic>? config,
  }) {
    return SupplierSupportSettingsModel(
      enabled: enabled ?? this.enabled,
      supplierRoles: supplierRoles ?? this.supplierRoles,
      config: config ?? this.config,
    );
  }

  @override
  List<Object?> get props => [enabled, supplierRoles, config];
}
