// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

import '../../../data/models/settings/feature_toggle_model.dart';
import '../../../data/models/settings/production_settings_model.dart';

class AppSettings extends Equatable {
  final List<FeatureToggleModel> featureToggles;
  final ProductionSettingsModel productionSettings;

  const AppSettings({
    required this.featureToggles,
    required this.productionSettings,
  });

  AppSettings copyWith({List<
      FeatureToggleModel>? featureToggles, ProductionSettingsModel? productionSettings}) {
    return AppSettings(
      featureToggles: featureToggles ?? this.featureToggles,
      productionSettings: productionSettings ?? this.productionSettings,
    );
  }

  @override
  List<Object?> get props => [featureToggles, productionSettings];
}
