// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

import 'feature_toggle.dart';
import 'production_settings.dart';

class AppSettings extends Equatable {
  final List<FeatureToggle> featureToggles;
  final ProductionSettings productionSettings;

  const AppSettings({
    required this.featureToggles,
    required this.productionSettings,
  });

  AppSettings copyWith({List<
      FeatureToggle>? featureToggles, ProductionSettings? productionSettings}) {
    return AppSettings(
      featureToggles: featureToggles ?? this.featureToggles,
      productionSettings: productionSettings ?? this.productionSettings,
    );
  }

  @override
  List<Object?> get props => [featureToggles, productionSettings];
}
