// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ExportImportSettings extends Equatable {
  final bool exportEnabled;
  final bool importEnabled;

  const ExportImportSettings({
    required this.exportEnabled,
    required this.importEnabled,
  });

  ExportImportSettings copyWith({bool? exportEnabled, bool? importEnabled}) {
    return ExportImportSettings(
      exportEnabled: exportEnabled ?? this.exportEnabled,
      importEnabled: importEnabled ?? this.importEnabled,
    );
  }

  @override
  List<Object?> get props => [exportEnabled, importEnabled];
}
