// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class FeatureToggle extends Equatable {
  final String featureKey;
  final bool enabled;

  const FeatureToggle({
    required this.featureKey,
    required this.enabled,
  });

  FeatureToggle copyWith({String? featureKey, bool? enabled}) {
    return FeatureToggle(
      featureKey: featureKey ?? this.featureKey,
      enabled: enabled ?? this.enabled,
    );
  }

  @override
  List<Object?> get props => [featureKey, enabled];
}
