// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class PasswordPolicy extends Equatable {
  final int minLength;
  final bool requireUppercase;
  final bool requireNumbers;
  final bool requireSpecialChars;
  final Duration? expiryDuration;

  const PasswordPolicy({
    required this.minLength,
    required this.requireUppercase,
    required this.requireNumbers,
    required this.requireSpecialChars,
    this.expiryDuration,
  });

  PasswordPolicy copyWith(
      {int? minLength, bool? requireUppercase, bool? requireNumbers, bool? requireSpecialChars, Duration?? expiryDuration}) {
    return PasswordPolicy(
      minLength: minLength ?? this.minLength,
      requireUppercase: requireUppercase ?? this.requireUppercase,
      requireNumbers: requireNumbers ?? this.requireNumbers,
      requireSpecialChars: requireSpecialChars ?? this.requireSpecialChars,
      expiryDuration: expiryDuration ?? this.expiryDuration,
    );
  }

  @override
  List<Object?> get props =>
      [
        minLength,
        requireUppercase,
        requireNumbers,
        requireSpecialChars,
        expiryDuration
      ];
}
