// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ProductionSettings extends Equatable {
  final bool allowReservation;
  final bool autoConsumeOnComplete;
  final int defaultYieldPerRun;

  const ProductionSettings({
    required this.allowReservation,
    required this.autoConsumeOnComplete,
    required this.defaultYieldPerRun,
  });

  ProductionSettings copyWith(
      {bool? allowReservation, bool? autoConsumeOnComplete, int? defaultYieldPerRun}) {
    return ProductionSettings(
      allowReservation: allowReservation ?? this.allowReservation,
      autoConsumeOnComplete: autoConsumeOnComplete ??
          this.autoConsumeOnComplete,
      defaultYieldPerRun: defaultYieldPerRun ?? this.defaultYieldPerRun,
    );
  }

  @override
  List<Object?> get props =>
      [allowReservation, autoConsumeOnComplete, defaultYieldPerRun];
}
