// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ReorderWorkflowSettings extends Equatable {
  final bool autoReorderEnabled;
  final int reorderPointMultiplier;
  final int maxPendingOrders;

  const ReorderWorkflowSettings({
    required this.autoReorderEnabled,
    required this.reorderPointMultiplier,
    required this.maxPendingOrders,
  });

  ReorderWorkflowSettings copyWith(
      {bool? autoReorderEnabled, int? reorderPointMultiplier, int? maxPendingOrders}) {
    return ReorderWorkflowSettings(
      autoReorderEnabled: autoReorderEnabled ?? this.autoReorderEnabled,
      reorderPointMultiplier: reorderPointMultiplier ??
          this.reorderPointMultiplier,
      maxPendingOrders: maxPendingOrders ?? this.maxPendingOrders,
    );
  }

  @override
  List<Object?> get props =>
      [autoReorderEnabled, reorderPointMultiplier, maxPendingOrders];
}
