// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class StockTakeSettings extends Equatable {
  final bool gpsEnforced;
  final double? maxDistanceMeters;
  final List<String>? allowedLocations;

  const StockTakeSettings({
    required this.gpsEnforced,
    this.maxDistanceMeters,
    this.allowedLocations,
  });

  StockTakeSettings copyWith(
      {bool? gpsEnforced, double? maxDistanceMeters, List<
          String>? allowedLocations}) {
    return StockTakeSettings(
      gpsEnforced: gpsEnforced ?? this.gpsEnforced,
      maxDistanceMeters: maxDistanceMeters ?? this.maxDistanceMeters,
      allowedLocations: allowedLocations ?? this.allowedLocations,
    );
  }

  @override
  List<Object?> get props => [gpsEnforced, maxDistanceMeters, allowedLocations];
}
