// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class SupplierSupportSettings extends Equatable {
  final bool enabled;
  final List<String>? supplierRoles;

  const SupplierSupportSettings({
    required this.enabled,
    this.supplierRoles,
  });

  SupplierSupportSettings copyWith(
      {bool? enabled, List<String>?? supplierRoles}) {
    return SupplierSupportSettings(
      enabled: enabled ?? this.enabled,
      supplierRoles: supplierRoles ?? this.supplierRoles,
    );
  }

  @override
  List<Object?> get props => [enabled, supplierRoles];
}
