// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ApprovalRequest extends Equatable {
  final String id;
  final String entityType;
  final String entityId;
  final String requestedBy;
  final String? approvedBy;
  final DateTime requestedAt;
  final DateTime? approvedAt;
  final String status;
  final String? reason;

  const ApprovalRequest({
    required this.id,
    required this.entityType,
    required this.entityId,
    required this.requestedBy,
    this.approvedBy,
    required this.requestedAt,
    this.approvedAt,
    required this.status,
    this.reason,
  });

  ApprovalRequest copyWith(
      {String? id, String? entityType, String? entityId, String? requestedBy, String?? approvedBy, DateTime? requestedAt, DateTime?? approvedAt, String? status, String?? reason}) {
    return ApprovalRequest(
      id: id ?? this.id,
      entityType: entityType ?? this.entityType,
      entityId: entityId ?? this.entityId,
      requestedBy: requestedBy ?? this.requestedBy,
      approvedBy: approvedBy ?? this.approvedBy,
      requestedAt: requestedAt ?? this.requestedAt,
      approvedAt: approvedAt ?? this.approvedAt,
      status: status ?? this.status,
      reason: reason ?? this.reason,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        entityType,
        entityId,
        requestedBy,
        approvedBy,
        requestedAt,
        approvedAt,
        status,
        reason
      ];
}
