// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class AuditLog extends Equatable {
  final String id;
  final String action;
  final String performedBy;
  final DateTime performedAt;

  const AuditLog({
    required this.id,
    required this.action,
    required this.performedBy,
    required this.performedAt,
  });

  AuditLog copyWith({
    String? id,
    String? action,
    String? performedBy,
    DateTime? performedAt,
  }) {
    return AuditLog(
      id: id ?? this.id,
      action: action ?? this.action,
      performedBy: performedBy ?? this.performedBy,
      performedAt: performedAt ?? this.performedAt,
    );
  }

  @override
  List<Object?> get props => [id, action, performedBy, performedAt];
}
