import '../../core/enums/stock_status.dart';
import '../../domain/entities/stock/stock.dart';

final List<Stock> mockStocks = [
  Stock(
    id: 'stk-001',
    name: 'Surgical Gloves - Medium',
    sku: 'GLV-MD-001',
    quantity: 120,
    description: 'Powder-free latex surgical gloves (Medium)',
    status: StockStatus.inStock,
    price: 5.00,
    costPrice: 3.00,
    categoryId: 'cat-medical',
    supplierId: 'sup-001',
    minimumStock: 50,
    maximumStock: 200,
    unit: 'Box',
    location: 'Aisle 1 - Shelf 3',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    updatedAt: DateTime.now(),
    durabilityType: StockDurabilityType.durable,
  ),

  Stock(
    id: 'stk-001',
    name: 'Surgical Gloves - Medium',
    sku: 'GLV-MD-001',
    quantity: 120,
    description: 'Powder-free latex surgical gloves (Medium)',
    status: StockStatus.inStock,
    price: 5.00,
    costPrice: 3.00,
    categoryId: 'cat-medical',
    supplierId: 'sup-001',
    minimumStock: 50,
    maximumStock: 200,
    unit: 'Box',
    location: 'Aisle 1 - Shelf 3',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    updatedAt: DateTime.now(),
    durabilityType: StockDurabilityType.durable,
  ),

  Stock(
    id: 'stk-001',
    name: 'Surgical Gloves - Medium',
    sku: 'GLV-MD-001',
    quantity: 120,
    description: 'Powder-free latex surgical gloves (Medium)',
    status: StockStatus.inStock,
    price: 5.00,
    costPrice: 3.00,
    categoryId: 'cat-medical',
    supplierId: 'sup-001',
    minimumStock: 50,
    maximumStock: 200,
    unit: 'Box',
    location: 'Aisle 1 - Shelf 3',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    updatedAt: DateTime.now(),
    durabilityType: StockDurabilityType.durable,
  ),

  Stock(
    id: 'stk-001',
    name: 'Surgical Gloves - Medium',
    sku: 'GLV-MD-001',
    quantity: 120,
    description: 'Powder-free latex surgical gloves (Medium)',
    status: StockStatus.inStock,
    price: 5.00,
    costPrice: 3.00,
    categoryId: 'cat-medical',
    supplierId: 'sup-001',
    minimumStock: 50,
    maximumStock: 200,
    unit: 'Box',
    location: 'Aisle 1 - Shelf 3',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    updatedAt: DateTime.now(),
    durabilityType: StockDurabilityType.durable,
  ),
  Stock(
    id: 'stk-002',
    name: 'Vitamin C Tablets 1000mg',
    sku: 'VITC-1000',
    quantity: 30,
    description: '1000mg Vitamin C, 60 tablets per bottle',
    status: StockStatus.inStock,
    price: 12.00,
    costPrice: 7.50,
    categoryId: 'cat-supplements',
    supplierId: 'sup-002',
    minimumStock: 40,
    maximumStock: 100,
    unit: 'Bottle',
    location: 'Aisle 3 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 12)),
    updatedAt: DateTime.now(),
    durabilityType: StockDurabilityType.nonPerishable,
  ),
  Stock(
    id: 'stk-003',
    name: 'Infrared Thermometer',
    sku: 'THRM-INFRA-01',
    quantity: 0,
    description: 'Non-contact infrared thermometer for clinical use',
    status: StockStatus.outOfStock,
    price: 45.00,
    costPrice: 30.00,
    categoryId: 'cat-devices',
    supplierId: 'sup-003',
    minimumStock: 10,
    maximumStock: 50,
    unit: 'Piece',
    location: 'Aisle 2 - Shelf 2',
    createdAt: DateTime.now().subtract(const Duration(days: 45)),
    updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    durabilityType: StockDurabilityType.nonPerishable,
  ),
  Stock(
    id: 'stk-004',
    name: 'Disposable Syringes 5ml',
    sku: 'SYR-5ML',
    quantity: 200,
    description: 'Sterile single-use syringes 5ml with needle',
    status: StockStatus.inStock,
    price: 0.50,
    costPrice: 0.20,
    categoryId: 'cat-medical',
    supplierId: 'sup-004',
    minimumStock: 100,
    maximumStock: 500,
    unit: 'Piece',
    location: 'Aisle 4 - Shelf 5',
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
    updatedAt: DateTime.now(),
    durabilityType: StockDurabilityType.nonPerishable,
  ),
  Stock(
    id: 'stk-005',
    name: 'N95 Face Masks',
    sku: 'N95-MASK-001',
    quantity: 15,
    description: 'N95 respiratory face masks, pack of 20',
    status: StockStatus.lowStock,
    price: 25.00,
    costPrice: 18.00,
    categoryId: 'cat-ppe',
    supplierId: 'sup-005',
    minimumStock: 20,
    maximumStock: 100,
    unit: 'Pack',
    location: 'Aisle 1 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 15)),
    updatedAt: DateTime.now().subtract(const Duration(hours: 6)),
    durabilityType: StockDurabilityType.consumable,
  ),
  Stock(
    id: 'stk-006',
    name: 'Digital Blood Pressure Monitor',
    sku: 'BP-MONITOR-001',
    quantity: 8,
    description: 'Automatic digital blood pressure monitor',
    status: StockStatus.inStock,
    price: 89.99,
    costPrice: 65.00,
    categoryId: 'cat-devices',
    supplierId: 'sup-003',
    minimumStock: 5,
    maximumStock: 25,
    unit: 'Piece',
    location: 'Aisle 2 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
    updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    durabilityType: StockDurabilityType.durable,
  ),
  Stock(
    id: 'stk-006',
    name: 'Digital Blood Pressure Monitor',
    sku: 'BP-MONITOR-001',
    quantity: 8,
    description: 'Automatic digital blood pressure monitor',
    status: StockStatus.inStock,
    price: 89.99,
    costPrice: 65.00,
    categoryId: 'cat-devices',
    supplierId: 'sup-003',
    minimumStock: 5,
    maximumStock: 25,
    unit: 'Piece',
    location: 'Aisle 2 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
    updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    durabilityType: StockDurabilityType.durable,
  ),
  Stock(
    id: 'stk-006',
    name: 'Digital Blood Pressure Monitor',
    sku: 'BP-MONITOR-001',
    quantity: 8,
    description: 'Automatic digital blood pressure monitor',
    status: StockStatus.inStock,
    price: 89.99,
    costPrice: 65.00,
    categoryId: 'cat-devices',
    supplierId: 'sup-003',
    minimumStock: 5,
    maximumStock: 25,
    unit: 'Piece',
    location: 'Aisle 2 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
    updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    durabilityType: StockDurabilityType.durable,
  ),
  Stock(
    id: 'stk-006',
    name: 'Digital Blood Pressure Monitor',
    sku: 'BP-MONITOR-001',
    quantity: 8,
    description: 'Automatic digital blood pressure monitor',
    status: StockStatus.inStock,
    price: 89.99,
    costPrice: 65.00,
    categoryId: 'cat-devices',
    supplierId: 'sup-003',
    minimumStock: 5,
    maximumStock: 25,
    unit: 'Piece',
    location: 'Aisle 2 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
    updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    durabilityType: StockDurabilityType.durable,
  ),
  Stock(
    id: 'stk-006',
    name: 'Digital Blood Pressure Monitor',
    sku: 'BP-MONITOR-001',
    quantity: 8,
    description: 'Automatic digital blood pressure monitor',
    status: StockStatus.inStock,
    price: 89.99,
    costPrice: 65.00,
    categoryId: 'cat-devices',
    supplierId: 'sup-003',
    minimumStock: 5,
    maximumStock: 25,
    unit: 'Piece',
    location: 'Aisle 2 - Shelf 1',
    createdAt: DateTime.now().subtract(const Duration(days: 8)),
    updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    durabilityType: StockDurabilityType.durable,
  ),
];


List<Stock> getMockStocks() => mockStocks;
