// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class PurchaseOrder extends Equatable {
  final String id;
  final String supplierId;
  final String createdByUserId;
  final String? approvedByUserId;
  final DateTime createdAt;
  final DateTime? expectedDeliveryDate;
  final DateTime? receivedDate;
  final String status;
  final List<PurchaseOrderItemModel> items;
  final String? notes;

  const PurchaseOrder({
    required this.id,
    required this.supplierId,
    required this.createdByUserId,
    this.approvedByUserId,
    required this.createdAt,
    this.expectedDeliveryDate,
    this.receivedDate,
    required this.status,
    required this.items,
    this.notes,
  });

  PurchaseOrder copyWith(
      {String? id, String? supplierId, String? createdByUserId, String?? approvedByUserId, DateTime? createdAt, DateTime?? expectedDeliveryDate, DateTime?? receivedDate, String? status, List<
          PurchaseOrderItemModel>? items, String?? notes}) {
    return PurchaseOrder(
      id: id ?? this.id,
      supplierId: supplierId ?? this.supplierId,
      createdByUserId: createdByUserId ?? this.createdByUserId,
      approvedByUserId: approvedByUserId ?? this.approvedByUserId,
      createdAt: createdAt ?? this.createdAt,
      expectedDeliveryDate: expectedDeliveryDate ?? this.expectedDeliveryDate,
      receivedDate: receivedDate ?? this.receivedDate,
      status: status ?? this.status,
      items: items ?? this.items,
      notes: notes ?? this.notes,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        supplierId,
        createdByUserId,
        approvedByUserId,
        createdAt,
        expectedDeliveryDate,
        receivedDate,
        status,
        items,
        notes
      ];
}
