// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/domain/entities/order/purchase_order_item.dart';
import 'package:equatable/equatable.dart';

class PurchaseOrder extends Equatable {
  final String id;
  final String supplierId;
  final String createdByUserId;
  final String? approvedByUserId;
  // Optional fields
  final String? goodsReceiptId;
  final String? invoiceId;
  final double totalAmount;
  final List<String>? attachments;
  final DateTime createdAt;
  final DateTime? expectedDeliveryDate;
  final DateTime? receivedDate;
  final String status;
  final List<PurchaseOrderItem> items;
  final String? notes;

  const PurchaseOrder({
    required this.id,
    required this.supplierId,
    required this.createdByUserId,
    this.approvedByUserId,
    this.goodsReceiptId,
    this.invoiceId,
    required this.totalAmount,
    this.attachments,
    required this.createdAt,
    this.expectedDeliveryDate,
    this.receivedDate,
    required this.status,
    required this.items,
    this.notes,
  });

  PurchaseOrder copyWith(
      {String? id, String? supplierId, String? createdByUserId, String? approvedByUserId, DateTime? createdAt, DateTime? expectedDeliveryDate, DateTime? receivedDate, String? status, List<
          PurchaseOrderItem>? items, String? notes}) {
    return PurchaseOrder(
      id: id ?? this.id,
      supplierId: supplierId ?? this.supplierId,
      createdByUserId: createdByUserId ?? this.createdByUserId,
      approvedByUserId: approvedByUserId ?? this.approvedByUserId,
      goodsReceiptId: goodsReceiptId ?? this.goodsReceiptId,
      invoiceId: invoiceId ?? this.invoiceId,
      totalAmount: totalAmount,
      attachments: attachments ?? this.attachments,
      createdAt: createdAt ?? this.createdAt,
      expectedDeliveryDate: expectedDeliveryDate ?? this.expectedDeliveryDate,
      receivedDate: receivedDate ?? this.receivedDate,
      status: status ?? this.status,
      items: items ?? this.items,
      notes: notes ?? this.notes,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        supplierId,
        createdByUserId,
        approvedByUserId,
        createdAt,
        expectedDeliveryDate,
        receivedDate,
        status,
        items,
        notes
      ];
}
