// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class PurchaseOrderItem extends Equatable {
  final String stockId;
  final int quantityOrdered;
  final int? quantityReceived;
  final double? unitCost;

  const PurchaseOrderItem({
    required this.stockId,
    required this.quantityOrdered,
    this.quantityReceived,
    this.unitCost,
  });

  PurchaseOrderItem copyWith(
      {String? stockId, int? quantityOrdered, int?? quantityReceived, double?? unitCost}) {
    return PurchaseOrderItem(
      stockId: stockId ?? this.stockId,
      quantityOrdered: quantityOrdered ?? this.quantityOrdered,
      quantityReceived: quantityReceived ?? this.quantityReceived,
      unitCost: unitCost ?? this.unitCost,
    );
  }

  @override
  List<Object?> get props =>
      [stockId, quantityOrdered, quantityReceived, unitCost];
}
