// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'purchase_order_item.dart';

class PurchaseOrderDraft extends Equatable {
  final String id;
  final String supplierId;
  final String createdByUserId;
  final DateTime createdAt;
  final List<PurchaseOrderItem> items;
  final String? notes;
  final bool autoGenerated;

  const PurchaseOrderDraft({
    required this.id,
    required this.supplierId,
    required this.createdByUserId,
    required this.createdAt,
    required this.items,
    this.notes,
    this.autoGenerated = false,
  });

  PurchaseOrderDraft copyWith({
    String? id,
    String? supplierId,
    String? createdByUserId,
    DateTime? createdAt,
    List<PurchaseOrderItem>? items,
    String? notes,
    bool? autoGenerated,
  }) {
    return PurchaseOrderDraft(
      id: id ?? this.id,
      supplierId: supplierId ?? this.supplierId,
      createdByUserId: createdByUserId ?? this.createdByUserId,
      createdAt: createdAt ?? this.createdAt,
      items: items ?? this.items,
      notes: notes ?? this.notes,
      autoGenerated: autoGenerated ?? this.autoGenerated,
    );
  }

  @override
  List<Object?> get props => [
    id,
    supplierId,
    createdByUserId,
    createdAt,
    items,
    notes,
    autoGenerated,
  ];
}
