// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ReturnOrder extends Equatable {
  final String id;
  final String originalOrderId;
  final String requestedByUserId;
  final DateTime requestedAt;
  final ReturnTypeModel type;
  final String? approvedByUserId;
  final DateTime? processedAt;
  final String status;
  final List<ReturnOrderItemModel> items;
  final String? notes;

  const ReturnOrder({
    required this.id,
    required this.originalOrderId,
    required this.requestedByUserId,
    required this.requestedAt,
    required this.type,
    this.approvedByUserId,
    this.processedAt,
    required this.status,
    required this.items,
    this.notes,
  });

  ReturnOrder copyWith(
      {String? id, String? originalOrderId, String? requestedByUserId, DateTime? requestedAt, ReturnTypeModel? type, String?? approvedByUserId, DateTime?? processedAt, String? status, List<
          ReturnOrderItemModel>? items, String?? notes}) {
    return ReturnOrder(
      id: id ?? this.id,
      originalOrderId: originalOrderId ?? this.originalOrderId,
      requestedByUserId: requestedByUserId ?? this.requestedByUserId,
      requestedAt: requestedAt ?? this.requestedAt,
      type: type ?? this.type,
      approvedByUserId: approvedByUserId ?? this.approvedByUserId,
      processedAt: processedAt ?? this.processedAt,
      status: status ?? this.status,
      items: items ?? this.items,
      notes: notes ?? this.notes,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        originalOrderId,
        requestedByUserId,
        requestedAt,
        type,
        approvedByUserId,
        processedAt,
        status,
        items,
        notes
      ];
}
