// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ReturnOrderItem extends Equatable {
  final String stockId;
  final int quantity;
  final String? reason;

  const ReturnOrderItem({
    required this.stockId,
    required this.quantity,
    this.reason,
  });

  ReturnOrderItem copyWith({String? stockId, int? quantity, String? reason}) {
    return ReturnOrderItem(
      stockId: stockId ?? this.stockId,
      quantity: quantity ?? this.quantity,
      reason: reason ?? this.reason,
    );
  }

  @override
  List<Object?> get props => [stockId, quantity, reason];
}
