// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';
import 'permission_type.dart';

class Role extends Equatable {
  final String id;
  final String name;
  final List<PermissionType> permissions;

  const Role({required this.id, required this.name, required this.permissions});

  Role copyWith({String? id, String? name, List<PermissionType>? permissions}) {
    return Role(
      id: id ?? this.id,
      name: name ?? this.name,
      permissions: permissions ?? this.permissions,
    );
  }

  @override
  List<Object?> get props => [id, name, permissions];
}
