// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/domain/entities/auth/permission_type.dart';
import 'package:clean_arch_app/domain/entities/auth/role.dart';
import 'package:equatable/equatable.dart';


class User extends Equatable {
  final String id;
  final String username;
  final String email;
  final List<Role> roles;
  final bool isActive;

  const User({
    required this.id,
    required this.username,
    required this.email,
    required this.roles,
    required this.isActive,
  });

  User copyWith({String? id, String? username, String? email, List<
      Role>? roles, bool? isActive}) {
    return User(
      id: id ?? this.id,
      username: username ?? this.username,
      email: email ?? this.email,
      roles: roles ?? this.roles,
      isActive: isActive ?? this.isActive,
    );
  }

  @override
  List<Object?> get props => [id, username, email, roles, isActive];

  Role get role => roles.first;

  hasPermission(PermissionType permission) {}
}
