// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ProductionOrder extends Equatable {
  final String id;
  final String productId;
  final int quantityToProduce;
  final String status;
  final DateTime createdAt;
  final DateTime? startedAt;
  final DateTime? completedAt;

  const ProductionOrder({
    required this.id,
    required this.productId,
    required this.quantityToProduce,
    required this.status,
    required this.createdAt,
    this.startedAt,
    this.completedAt,
  });

  ProductionOrder copyWith(
      {String? id, String? productId, int? quantityToProduce, String? status, DateTime? createdAt, DateTime?? startedAt, DateTime?? completedAt}) {
    return ProductionOrder(
      id: id ?? this.id,
      productId: productId ?? this.productId,
      quantityToProduce: quantityToProduce ?? this.quantityToProduce,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        productId,
        quantityToProduce,
        status,
        createdAt,
        startedAt,
        completedAt
      ];
}
