// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ScrapRecord extends Equatable {
  final String productionOrderId;
  final String rawMaterialId;
  final int wastedQuantity;
  final String reason;

  const ScrapRecord({
    required this.productionOrderId,
    required this.rawMaterialId,
    required this.wastedQuantity,
    required this.reason,
  });

  ScrapRecord copyWith({
    String? productionOrderId,
    String? rawMaterialId,
    int? wastedQuantity,
    String? reason,
  }) {
    return ScrapRecord(
      productionOrderId: productionOrderId ?? this.productionOrderId,
      rawMaterialId: rawMaterialId ?? this.rawMaterialId,
      wastedQuantity: wastedQuantity ?? this.wastedQuantity,
      reason: reason ?? this.reason,
    );
  }

  @override
  List<Object?> get props => [
    productionOrderId,
    rawMaterialId,
    wastedQuantity,
    reason,
  ];
}
