// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/auth/permission_type_model.dart';
import 'package:clean_arch_app/domain/entities/auth/permission_type.dart';

class PermissionTypeMapper {
  static PermissionType toEntity(PermissionTypeModel model) =>
      PermissionType.values.byName(model.name);

  static PermissionTypeModel fromEntity(PermissionType entity) =>
      PermissionTypeModel.values.byName(entity.name);

  static List<PermissionType> toEntityList(List<PermissionTypeModel> models) =>
      models.map(toEntity).toList();

  static List<PermissionTypeModel> fromEntityList(
    List<PermissionType> entities,
  ) => entities.map(fromEntity).toList();
}
