// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/auth/role_model.dart';
import 'package:clean_arch_app/domain/entities/auth/role.dart';

import 'permission_type_mapper.dart';

class RoleMapper {
  static Role toEntity(RoleModel model) {
    return Role(
      id: model.id,
      name: model.name,
      permissions: model.permissions
          .map((e) => PermissionTypeMapper.toEntity(e))
          .toList(),
    );
  }

  static RoleModel fromEntity(Role entity) {
    return RoleModel(
      id: entity.id,
      name: entity.name,
      permissions: entity.permissions
          .map((e) => PermissionTypeMapper.fromEntity(e))
          .toList(),
    );
  }
}

