// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/userModel.dart';
import 'package:clean_arch_app/domain/entities/user.dart';

class UserMapper {
  static User toEntity(UserModel model) {
    return User(
      id: model.id,
      username: model.username,
      email: model.email,
      roles: model.roles.map((e) => RoleMapper.toEntity(e)).toList(),
      isActive: model.isActive,
    );
  }

  static UserModel fromEntity(User entity) {
    return UserModel(
      id: entity.id,
      username: entity.username,
      email: entity.email,
      roles: entity.roles.map((e) => RoleMapper.fromEntity(e)).toList(),
      isActive: entity.isActive,
    );
  }
}
