// GENERATED BY AMAR SCRIPT – EDIT MODEL

import '../../../domain/entities/activity/activity.dart';
import '../../models/activity/activity_model.dart';

class ActivityMapper {
  static Activity toEntity(ActivityModel model) {
    return Activity(
      id: model.id,
      action: model.action,
      entityType: model.entityType,
      entityId: model.entityId,
      userId: model.userId,
      timestamp: model.timestamp,
      metadata: model.metadata,
    );
  }

  static ActivityModel fromEntity(Activity entity) {
    return ActivityModel(
      id: entity.id,
      action: entity.action,
      entityType: entity.entityType,
      entityId: entity.entityId,
      userId: entity.userId,
      timestamp: entity.timestamp,
      metadata: entity.metadata,
    );
  }
}
