// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/activityModel.dart';
import 'package:clean_arch_app/domain/entities/activity.dart';

class ActivityMapper {
  static Activity toEntity(ActivityModel model) {
    return Activity(
      id: model.id,
      action: model.action,
      entityType: model.entityType,
      entityId: model.entityId,
      userId: model.userId,
      timestamp: model.timestamp,
    );
  }

  static ActivityModel fromEntity(Activity entity) {
    return ActivityModel(
      id: entity.id,
      action: entity.action,
      entityType: entity.entityType,
      entityId: entity.entityId,
      userId: entity.userId,
      timestamp: entity.timestamp,
    );
  }
}
