// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/domain/entities/production/production_order.dart';

import '../../models/production/production_order_model.dart';

class ProductionOrderMapper {
  static ProductionOrder toEntity(ProductionOrderModel model) {
    return ProductionOrder(
      id: model.id,
      productId: model.productId,
      quantityToProduce: model.quantityToProduce,
      status: model.status,
      createdAt: model.createdAt,
      startedAt: model.startedAt,
      completedAt: model.completedAt,
    );
  }

  static ProductionOrderModel fromEntity(ProductionOrder entity) {
    return ProductionOrderModel(
      id: entity.id,
      productId: entity.productId,
      quantityToProduce: entity.quantityToProduce,
      status: entity.status,
      createdAt: entity.createdAt,
      startedAt: entity.startedAt,
      completedAt: entity.completedAt,
    );
  }
}
