// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/models/production/scrap_record_model.dart';

import '../../../domain/entities/production/scrap_record.dart';

class ScrapRecordMapper {
  static ScrapRecord toEntity(ScrapRecordModel model) {
    return ScrapRecord(
      productionOrderId: model.productionOrderId,
      rawMaterialId: model.rawMaterialId,
      wastedQuantity: model.wastedQuantity,
      reason: model.reason,
    );
  }

  static ScrapRecordModel fromEntity(ScrapRecord entity) {
    return ScrapRecordModel(
      productionOrderId: entity.productionOrderId,
      rawMaterialId: entity.rawMaterialId,
      wastedQuantity: entity.wastedQuantity,
      reason: entity.reason,
    );
  }
}
