// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Location extends Equatable {
  final String id;
  final String name;
  final String? description;
  final double? latitude;
  final double? longitude;

  const Location({
    required this.id,
    required this.name,
    this.description,
    this.latitude,
    this.longitude,
  });

  Location copyWith(
      {String? id, String? name, String? description, double? latitude, double? longitude}) {
    return Location(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
    );
  }

  @override
  List<Object?> get props => [id, name, description, latitude, longitude];
}
