// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Unit extends Equatable {
  final String id;
  final String name;
  final String? description;
  final double? conversionRate;

  const Unit({
    required this.id,
    required this.name,
    this.description,
    this.conversionRate,
  });

  Unit copyWith(
      {String? id, String? name, String?? description, double?? conversionRate}) {
    return Unit(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      conversionRate: conversionRate ?? this.conversionRate,
    );
  }

  @override
  List<Object?> get props => [id, name, description, conversionRate];
}
