// GENERATED BY AMAR SCRIPT – EDIT
import 'package:clean_arch_app/data/models/sales/customer_model.dart';

import '../../../domain/entities/sales/customer.dart' show Customer;

class CustomerMapper {
  static Customer toEntity(CustomerModel model) {
    return Customer(
      id: model.id,
      name: model.name,
      email: model.email,
      phone: model.phone,
      loyaltyId: model.loyaltyId,
    );
  }

  static CustomerModel fromEntity(Customer entity) {
    return CustomerModel(
      id: entity.id,
      name: entity.name,
      email: entity.email,
      phone: entity.phone,
      loyaltyId: entity.loyaltyId,
    );
  }
}
