// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/salesOrderModel.dart';
import 'package:clean_arch_app/domain/entities/salesOrder.dart';

class SalesOrderMapper {
  static SalesOrder toEntity(SalesOrderModel model) {
    return SalesOrder(
      id: model.id,
      customerId: model.customerId,
      createdByUserId: model.createdByUserId,
      createdAt: model.createdAt,
      status: model.status,
      items: model.items.map((e) => SalesOrderItemMapper.toEntity(e)).toList(),
      totalAmount: model.totalAmount,
      notes: model.notes,
    );
  }

  static SalesOrderModel fromEntity(SalesOrder entity) {
    return SalesOrderModel(
      id: entity.id,
      customerId: entity.customerId,
      createdByUserId: entity.createdByUserId,
      createdAt: entity.createdAt,
      status: entity.status,
      items: entity.items
          .map((e) => SalesOrderItemMapper.fromEntity(e))
          .toList(),
      totalAmount: entity.totalAmount,
      notes: entity.notes,
    );
  }
}
