// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/sales/sales_order_item_model.dart';
import 'package:stocktrack_pro/domain/entities/sales/sales_order_item.dart';

class SalesOrderItemMapper {
  static SalesOrderItem toEntity(SalesOrderItemModel model) {
    return SalesOrderItem(
      stockId: model.stockId,
      quantity: model.quantity,
      unitPrice: model.unitPrice,
    );
  }

  static SalesOrderItemModel fromEntity(SalesOrderItem entity) {
    return SalesOrderItemModel(
      stockId: entity.stockId,
      quantity: entity.quantity,
      unitPrice: entity.unitPrice,
    );
  }
}
