// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/models/sales/sales_return_model.dart';
import 'package:clean_arch_app/domain/entities/sales/sales_return.dart';

import 'sales_order_item_mapper.dart';

class SalesReturnMapper {
  static SalesReturn toEntity(SalesReturnModel model) {
    return SalesReturn(
      id: model.id,
      salesOrderId: model.salesOrderId,
      returnedByUserId: model.returnedByUserId,
      returnedAt: model.returnedAt,
      items: model.items.map((e) => SalesOrderItemMapper.toEntity(e)).toList(),
      refundAmount: model.refundAmount,
      reason: model.reason,
      status: model.status,
    );
  }

  static SalesReturnModel fromEntity(SalesReturn entity) {
    return SalesReturnModel(
      id: entity.id,
      salesOrderId: entity.salesOrderId,
      returnedByUserId: entity.returnedByUserId,
      returnedAt: entity.returnedAt,
      items: entity.items
          .map((e) => SalesOrderItemMapper.fromEntity(e))
          .toList(),
      refundAmount: entity.refundAmount,
      reason: entity.reason,
      status: entity.status,
    );
  }
}
