// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/salesOrderItemModel.dart';
import 'package:clean_arch_app/domain/entities/salesOrderItem.dart';

class SalesOrderItemMapper {
  static SalesOrderItem toEntity(SalesOrderItemModel model) {
    return SalesOrderItem(
      stockId: model.stockId,
      quantity: model.quantity,
      unitPrice: model.unitPrice,
    );
  }

  static SalesOrderItemModel fromEntity(SalesOrderItem entity) {
    return SalesOrderItemModel(
      stockId: entity.stockId,
      quantity: entity.quantity,
      unitPrice: entity.unitPrice,
    );
  }
}
