// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Activity extends Equatable {
  final String id;
  final String action;
  final String entityType;
  final String entityId;
  final String userId;
  final DateTime timestamp;
  final Map<String, dynamic> metadata;

  const Activity({
    required this.id,
    required this.action,
    required this.entityType,
    required this.entityId,
    required this.userId,
    required this.timestamp,
    required this.metadata,
  });

  Activity copyWith(
      {String? id, String? action, String? entityType, String? entityId, String? userId, DateTime? timestamp, Map<
          String,
          dynamic>? metadata}) {
    return Activity(
      id: id ?? this.id,
      action: action ?? this.action,
      entityType: entityType ?? this.entityType,
      entityId: entityId ?? this.entityId,
      userId: userId ?? this.userId,
      timestamp: timestamp ?? this.timestamp,
      metadata: metadata ?? this.metadata,
    );
  }

  @override
  List<Object?> get props =>
      [id, action, entityType, entityId, userId, timestamp, metadata];
}
