// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVgpOeW4gXPcjomrOAPj8VkIRouaL_Yg',
    appId: '1:103793370884:web:a8f65607ce3f9f78561251',
    messagingSenderId: '103793370884',
    projectId: 'stocktrack-pro-8754b',
    authDomain: 'stocktrack-pro-8754b.firebaseapp.com',
    storageBucket: 'stocktrack-pro-8754b.firebasestorage.app',
    measurementId: 'G-YLH1JWLDVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_XMA2Il1ikSU0AxUxz09orM_Eeiqpbc',
    appId: '1:103793370884:android:826065a66a4424ab561251',
    messagingSenderId: '103793370884',
    projectId: 'stocktrack-pro-8754b',
    storageBucket: 'stocktrack-pro-8754b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxxSEL3OGrNqNu9H1_Lmo2CPJmNfGOOg',
    appId: '1:103793370884:ios:53e836af91d93990561251',
    messagingSenderId: '103793370884',
    projectId: 'stocktrack-pro-8754b',
    storageBucket: 'stocktrack-pro-8754b.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxxSEL3OGrNqNu9H1_Lmo2CPJmNfGOOg',
    appId: '1:103793370884:ios:53e836af91d93990561251',
    messagingSenderId: '103793370884',
    projectId: 'stocktrack-pro-8754b',
    storageBucket: 'stocktrack-pro-8754b.firebasestorage.app',
    iosBundleId: 'com.example.cleanArchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKVgpOeW4gXPcjomrOAPj8VkIRouaL_Yg',
    appId: '1:103793370884:web:fdf007134c072d1b561251',
    messagingSenderId: '103793370884',
    projectId: 'stocktrack-pro-8754b',
    authDomain: 'stocktrack-pro-8754b.firebaseapp.com',
    storageBucket: 'stocktrack-pro-8754b.firebasestorage.app',
    measurementId: 'G-K9NL68620W',
  );
}
