// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'purchase_order_draft.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PurchaseOrderDraftModel _$PurchaseOrderDraftModelFromJson(
  Map<String, dynamic> json,
) => PurchaseOrderDraftModel(
  id: json['id'] as String,
  supplierId: json['supplierId'] as String,
  createdByUserId: json['createdByUserId'] as String,
  createdAt: DateTime.parse(json['createdAt'] as String),
  items: (json['items'] as List<dynamic>)
      .map((e) => PurchaseOrderItemModel.fromJson(e as Map<String, dynamic>))
      .toList(),
  notes: json['notes'] as String?,
  autoGenerated: json['autoGenerated'] as bool? ?? false,
);

Map<String, dynamic> _$PurchaseOrderDraftModelToJson(
  PurchaseOrderDraftModel instance,
) => <String, dynamic>{
  'id': instance.id,
  'supplierId': instance.supplierId,
  'createdByUserId': instance.createdByUserId,
  'createdAt': instance.createdAt.toIso8601String(),
  'items': instance.items.map((e) => e.toJson()).toList(),
  'notes': instance.notes,
  'autoGenerated': instance.autoGenerated,
};
