import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import '../../../domain/entities/order/purchase_order_draft.dart';
import 'purchase_order_item_model.dart';

part 'purchase_order_draft.g.dart';

@JsonSerializable(explicitToJson: true)
class PurchaseOrderDraftModel extends Equatable {
  final String id;
  final String supplierId;
  final String createdByUserId;
  final DateTime createdAt;
  final List<PurchaseOrderItemModel> items;
  final String? notes;
  final bool autoGenerated;

  const PurchaseOrderDraftModel({
    required this.id,
    required this.supplierId,
    required this.createdByUserId,
    required this.createdAt,
    required this.items,
    this.notes,
    this.autoGenerated = false,
  });

  factory PurchaseOrderDraftModel.fromJson(Map<String, dynamic> json) =>
      _$PurchaseOrderDraftModelFromJson(json);

  Map<String, dynamic> toJson() => _$PurchaseOrderDraftModelToJson(this);

  PurchaseOrderDraft toDomain() => PurchaseOrderDraft(
    id: id,
    supplierId: supplierId,
    createdByUserId: createdByUserId,
    createdAt: createdAt,
    items: items.map((m) => m.toDomain()).toList(),
    notes: notes,
    autoGenerated: autoGenerated,
  );

  static PurchaseOrderDraftModel fromDomain(PurchaseOrderDraft ent) =>
      PurchaseOrderDraftModel(
        id: ent.id,
        supplierId: ent.supplierId,
        createdByUserId: ent.createdByUserId,
        createdAt: ent.createdAt,
        items: ent.items.map(PurchaseOrderItemModel.fromDomain).toList(),
        notes: ent.notes,
        autoGenerated: ent.autoGenerated,
      );

  PurchaseOrderDraftModel copyWith({
    String? id,
    String? supplierId,
    String? createdByUserId,
    DateTime? createdAt,
    List<PurchaseOrderItemModel>? items,
    String? notes,
    bool? autoGenerated,
  }) {
    return PurchaseOrderDraftModel(
      id: id ?? this.id,
      supplierId: supplierId ?? this.supplierId,
      createdByUserId: createdByUserId ?? this.createdByUserId,
      createdAt: createdAt ?? this.createdAt,
      items: items ?? this.items,
      notes: notes ?? this.notes,
      autoGenerated: autoGenerated ?? this.autoGenerated,
    );
  }

  @override
  List<Object?> get props => [
    id,
    supplierId,
    createdByUserId,
    createdAt,
    items,
    notes,
    autoGenerated,
  ];
}
