// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/order/purchase_order_model.dart';
import 'package:clean_arch_app/domain/entities/order/purchase_order.dart';

import 'purchase_order_item_mapper.dart';

class PurchaseOrderMapper {
  static PurchaseOrder toEntity(PurchaseOrderModel model) {
    return PurchaseOrder(
      id: model.id,
      supplierId: model.supplierId,
      createdByUserId: model.createdByUserId,
      approvedByUserId: model.approvedByUserId,
      goodsReceiptId: model.goodsReceiptId,
      invoiceId: model.invoiceId,
      totalAmount: model.totalAmount,
      attachments: model.attachments,
      createdAt: model.createdAt,
      expectedDeliveryDate: model.expectedDeliveryDate,
      receivedDate: model.receivedDate,
      status: model.status,
      items: model.items
          .map((e) => PurchaseOrderItemMapper.toEntity(e))
          .toList(),
      notes: model.notes,
    );
  }

  static PurchaseOrderModel fromEntity(PurchaseOrder entity) {
    return PurchaseOrderModel(
      id: entity.id,
      supplierId: entity.supplierId,
      createdByUserId: entity.createdByUserId,
      approvedByUserId: entity.approvedByUserId,
      goodsReceiptId: entity.goodsReceiptId,
      invoiceId: entity.invoiceId,
      totalAmount: entity.totalAmount,
      attachments: entity.attachments,
      createdAt: entity.createdAt,
      expectedDeliveryDate: entity.expectedDeliveryDate,
      receivedDate: entity.receivedDate,
      status: entity.status,
      items: entity.items
          .map((e) => PurchaseOrderItemMapper.fromEntity(e))
          .toList(),
      notes: entity.notes,
    );
  }
}
