// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/models/order/purchase_order_item_model.dart';
import 'package:clean_arch_app/domain/entities/order/purchase_order_item.dart';

class PurchaseOrderItemMapper {
  static PurchaseOrderItem toEntity(PurchaseOrderItemModel model) {
    return PurchaseOrderItem(
      stockId: model.stockId,
      quantityOrdered: model.quantityOrdered,
      quantityReceived: model.quantityReceived,
      unitCost: model.unitCost,
    );
  }

  static PurchaseOrderItemModel fromEntity(PurchaseOrderItem entity) {
    return PurchaseOrderItemModel(
      stockId: entity.stockId,
      quantityOrdered: entity.quantityOrdered,
      quantityReceived: entity.quantityReceived,
      unitCost: entity.unitCost,
    );
  }
}
