// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/order/return_type_model.dart';
import 'package:clean_arch_app/domain/entities/order/return_type.dart';

class ReturnTypeMapper {
  static ReturnType toEntity(ReturnTypeModel model) =>
      ReturnType.values.byName(model.name);

  static ReturnTypeModel fromEntity(ReturnType entity) =>
      ReturnTypeModel.values.byName(entity.name);

  static List<ReturnType> toEntityList(List<ReturnTypeModel> models) =>
      models.map(toEntity).toList();

  static List<ReturnTypeModel> fromEntityList(List<ReturnType> entities) =>
      entities.map(fromEntity).toList();
}
