// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:stocktrack_pro/data/models/order/return_order_item_model.dart';
import 'package:stocktrack_pro/domain/entities/order/return_order_item.dart';

class ReturnOrderItemMapper {
  static ReturnOrderItem toEntity(ReturnOrderItemModel model) {
    return ReturnOrderItem(
      stockId: model.stockId,
      quantity: model.quantity,
      reason: model.reason,
    );
  }

  static ReturnOrderItemModel fromEntity(ReturnOrderItem entity) {
    return ReturnOrderItemModel(
      stockId: entity.stockId,
      quantity: entity.quantity,
      reason: entity.reason,
    );
  }
}
