// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:stocktrack_pro/data/models/order/return_order_model.dart';
import 'package:stocktrack_pro/domain/entities/order/return_order.dart';

import 'return_order_item_mapper.dart';
import 'return_type_mapper.dart';

class ReturnOrderMapper {
  static ReturnOrder toEntity(ReturnOrderModel model) {
    return ReturnOrder(
      id: model.id,
      originalOrderId: model.originalOrderId,
      requestedByUserId: model.requestedByUserId,
      requestedAt: model.requestedAt,
      type: ReturnTypeMapper.toEntity(model.type!),
      approvedByUserId: model.approvedByUserId,
      processedAt: model.processedAt,
      status: model.status,
      items: model.items.map((e) => ReturnOrderItemMapper.toEntity(e)).toList(),
      notes: model.notes,
    );
  }

  static ReturnOrderModel fromEntity(ReturnOrder entity) {
    return ReturnOrderModel(
      id: entity.id,
      originalOrderId: entity.originalOrderId,
      requestedByUserId: entity.requestedByUserId,
      requestedAt: entity.requestedAt,
      type: ReturnTypeMapper.fromEntity(entity.type!),
      approvedByUserId: entity.approvedByUserId,
      processedAt: entity.processedAt,
      status: entity.status,
      items: entity.items
          .map((e) => ReturnOrderItemMapper.fromEntity(e))
          .toList(),
      notes: entity.notes,
    );
  }
}
