// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/returnOrderItemModel.dart';
import 'package:clean_arch_app/domain/entities/returnOrderItem.dart';

class ReturnOrderItemMapper {
  static ReturnOrderItem toEntity(ReturnOrderItemModel model) {
    return ReturnOrderItem(
      stockId: model.stockId,
      quantity: model.quantity,
      reason: model.reason,
    );
  }

  static ReturnOrderItemModel fromEntity(ReturnOrderItem entity) {
    return ReturnOrderItemModel(
      stockId: entity.stockId,
      quantity: entity.quantity,
      reason: entity.reason,
    );
  }
}
