// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/locationModel.dart';
import 'package:clean_arch_app/domain/entities/location.dart';

class LocationMapper {
  static Location toEntity(LocationModel model) {
    return Location(
      id: model.id,
      name: model.name,
      description: model.description,
      latitude: model.latitude,
      longitude: model.longitude,
    );
  }

  static LocationModel fromEntity(Location entity) {
    return LocationModel(
      id: entity.id,
      name: entity.name,
      description: entity.description,
      latitude: entity.latitude,
      longitude: entity.longitude,
    );
  }
}
