// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/notificationModel.dart';
import 'package:clean_arch_app/domain/entities/notification.dart';

class NotificationMapper {
  static Notification toEntity(NotificationModel model) {
    return Notification(
      id: model.id,
      userId: model.userId,
      title: model.title,
      message: model.message,
      read: model.read,
      createdAt: model.createdAt,
    );
  }

  static NotificationModel fromEntity(Notification entity) {
    return NotificationModel(
      id: entity.id,
      userId: entity.userId,
      title: entity.title,
      message: entity.message,
      read: entity.read,
      createdAt: entity.createdAt,
    );
  }
}
