// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/general/unit_model.dart';
import 'package:stocktrack_pro/domain/entities/general/unit.dart';

class UnitMapper {
  static Unit toEntity(UnitModel model) {
    return Unit(
      id: model.id,
      name: model.name,
      description: model.description,
      conversionRate: model.conversionRate,
    );
  }

  static UnitModel fromEntity(Unit entity) {
    return UnitModel(
      id: entity.id,
      name: entity.name,
      description: entity.description,
      conversionRate: entity.conversionRate,
    );
  }
}
