// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ExpiryReport extends Equatable {
  final String stockId;
  final String name;
  final DateTime expiryDate;
  final int daysToExpiry;
  final int quantity;

  const ExpiryReport({
    required this.stockId,
    required this.name,
    required this.expiryDate,
    required this.daysToExpiry,
    required this.quantity,
  });

  ExpiryReport copyWith(
      {String? stockId, String? name, DateTime? expiryDate, int? daysToExpiry, int? quantity}) {
    return ExpiryReport(
      stockId: stockId ?? this.stockId,
      name: name ?? this.name,
      expiryDate: expiryDate ?? this.expiryDate,
      daysToExpiry: daysToExpiry ?? this.daysToExpiry,
      quantity: quantity ?? this.quantity,
    );
  }

  @override
  List<Object?> get props =>
      [stockId, name, expiryDate, daysToExpiry, quantity];
}
