// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class ReorderReport extends Equatable {
  final String stockId;
  final String name;
  final int quantity;
  final int minimumStock;
  final bool needsReorder;

  const ReorderReport({
    required this.stockId,
    required this.name,
    required this.quantity,
    required this.minimumStock,
    required this.needsReorder,
  });

  ReorderReport copyWith({
    String? stockId,
    String? name,
    int? quantity,
    int? minimumStock,
    bool? needsReorder,
  }) {
    return ReorderReport(
      stockId: stockId ?? this.stockId,
      name: name ?? this.name,
      quantity: quantity ?? this.quantity,
      minimumStock: minimumStock ?? this.minimumStock,
      needsReorder: needsReorder ?? this.needsReorder,
    );
  }

  @override
  List<Object?> get props => [
    stockId,
    name,
    quantity,
    minimumStock,
    needsReorder,
  ];
}
