// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class StockOutReport extends Equatable {
  final String stockId;
  final String name;
  final int quantityOut;
  final DateTime dateOut;
  final String performedBy;
  final String? reason;

  const StockOutReport({
    required this.stockId,
    required this.name,
    required this.quantityOut,
    required this.dateOut,
    required this.performedBy,
    this.reason,
  });

  StockOutReport copyWith({
    String? stockId,
    String? name,
    int? quantityOut,
    DateTime? dateOut,
    String? performedBy,
    String? reason,
  }) {
    return StockOutReport(
      stockId: stockId ?? this.stockId,
      name: name ?? this.name,
      quantityOut: quantityOut ?? this.quantityOut,
      dateOut: dateOut ?? this.dateOut,
      performedBy: performedBy ?? this.performedBy,
      reason: reason ?? this.reason,
    );
  }

  @override
  List<Object?> get props => [
    stockId,
    name,
    quantityOut,
    dateOut,
    performedBy,
    reason,
  ];
}
