// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class StockMovementReport extends Equatable {
  final String movementId;
  final String stockId;
  final String type;
  final int quantity;
  final String performedBy;
  final DateTime timestamp;
  final String? reason;

  const StockMovementReport({
    required this.movementId,
    required this.stockId,
    required this.type,
    required this.quantity,
    required this.performedBy,
    required this.timestamp,
    this.reason,
  });

  StockMovementReport copyWith(
      {String? movementId, String? stockId, String? type, int? quantity, String? performedBy, DateTime? timestamp, String? reason}) {
    return StockMovementReport(
      movementId: movementId ?? this.movementId,
      stockId: stockId ?? this.stockId,
      type: type ?? this.type,
      quantity: quantity ?? this.quantity,
      performedBy: performedBy ?? this.performedBy,
      timestamp: timestamp ?? this.timestamp,
      reason: reason ?? this.reason,
    );
  }

  @override
  List<Object?> get props =>
      [movementId, stockId, type, quantity, performedBy, timestamp, reason];
}
