// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/approvalRequestModel.dart';
import 'package:clean_arch_app/domain/entities/approvalRequest.dart';

class ApprovalRequestMapper {
  static ApprovalRequest toEntity(ApprovalRequestModel model) {
    return ApprovalRequest(
      id: model.id,
      entityType: model.entityType,
      entityId: model.entityId,
      requestedBy: model.requestedBy,
      approvedBy: model.approvedBy,
      requestedAt: model.requestedAt,
      approvedAt: model.approvedAt,
      status: model.status,
      reason: model.reason,
    );
  }

  static ApprovalRequestModel fromEntity(ApprovalRequest entity) {
    return ApprovalRequestModel(
      id: entity.id,
      entityType: entity.entityType,
      entityId: entity.entityId,
      requestedBy: entity.requestedBy,
      approvedBy: entity.approvedBy,
      requestedAt: entity.requestedAt,
      approvedAt: entity.approvedAt,
      status: entity.status,
      reason: entity.reason,
    );
  }
}
