// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/auditLogModel.dart';
import 'package:clean_arch_app/domain/entities/auditLog.dart';

class AuditLogMapper {
  static AuditLog toEntity(AuditLogModel model) {
    return AuditLog(
      id: model.id,
      action: model.action,
      performedBy: model.performedBy,
      performedAt: model.performedAt,
    );
  }

  static AuditLogModel fromEntity(AuditLog entity) {
    return AuditLogModel(
      id: entity.id,
      action: entity.action,
      performedBy: entity.performedBy,
      performedAt: entity.performedAt,
    );
  }
}
