// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/appSettingsModel.dart';
import 'package:clean_arch_app/domain/entities/appSettings.dart';

class AppSettingsMapper {
  static AppSettings toEntity(AppSettingsModel model) {
    return AppSettings(
      featureToggles: model.featureToggles
          .map((e) => FeatureToggleMapper.toEntity(e))
          .toList(),
      productionSettings: ProductionSettingsMapper.toEntity(
        model.productionSettings!,
      ),
    );
  }

  static AppSettingsModel fromEntity(AppSettings entity) {
    return AppSettingsModel(
      featureToggles: entity.featureToggles
          .map((e) => FeatureToggleMapper.fromEntity(e))
          .toList(),
      productionSettings: ProductionSettingsMapper.fromEntity(
        entity.productionSettings!,
      ),
    );
  }
}
