// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/exportImportSettingsModel.dart';
import 'package:clean_arch_app/domain/entities/exportImportSettings.dart';

class ExportImportSettingsMapper {
  static ExportImportSettings toEntity(ExportImportSettingsModel model) {
    return ExportImportSettings(
      exportEnabled: model.exportEnabled,
      importEnabled: model.importEnabled,
    );
  }

  static ExportImportSettingsModel fromEntity(ExportImportSettings entity) {
    return ExportImportSettingsModel(
      exportEnabled: entity.exportEnabled,
      importEnabled: entity.importEnabled,
    );
  }
}
