// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/settings/feature_toggle_model.dart';
import 'package:stocktrack_pro/domain/entities/settings/feature_toggle.dart';

class FeatureToggleMapper {
  static FeatureToggle toEntity(FeatureToggleModel model) {
    return FeatureToggle(
      featureKey: model.featureKey,
      enabled: model.enabled,
    );
  }

  static FeatureToggleModel fromEntity(FeatureToggle entity) {
    return FeatureToggleModel(
      featureKey: entity.featureKey,
      enabled: entity.enabled,
    );
  }
}
