// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/passwordPolicyModel.dart';
import 'package:clean_arch_app/domain/entities/passwordPolicy.dart';

class PasswordPolicyMapper {
  static PasswordPolicy toEntity(PasswordPolicyModel model) {
    return PasswordPolicy(
      minLength: model.minLength,
      requireUppercase: model.requireUppercase,
      requireNumbers: model.requireNumbers,
      requireSpecialChars: model.requireSpecialChars,
      expiryDuration: model.expiryDuration,
    );
  }

  static PasswordPolicyModel fromEntity(PasswordPolicy entity) {
    return PasswordPolicyModel(
      minLength: entity.minLength,
      requireUppercase: entity.requireUppercase,
      requireNumbers: entity.requireNumbers,
      requireSpecialChars: entity.requireSpecialChars,
      expiryDuration: entity.expiryDuration,
    );
  }
}
