// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/productionSettingsModel.dart';
import 'package:clean_arch_app/domain/entities/productionSettings.dart';

class ProductionSettingsMapper {
  static ProductionSettings toEntity(ProductionSettingsModel model) {
    return ProductionSettings(
      allowReservation: model.allowReservation,
      autoConsumeOnComplete: model.autoConsumeOnComplete,
      defaultYieldPerRun: model.defaultYieldPerRun,
    );
  }

  static ProductionSettingsModel fromEntity(ProductionSettings entity) {
    return ProductionSettingsModel(
      allowReservation: entity.allowReservation,
      autoConsumeOnComplete: entity.autoConsumeOnComplete,
      defaultYieldPerRun: entity.defaultYieldPerRun,
    );
  }
}
