// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/models/settings/reorder_workflow_settings_model.dart';
import 'package:clean_arch_app/domain/entities/settings/reorder_workflow_settings.dart';

class ReorderWorkflowSettingsMapper {
  static ReorderWorkflowSettings toEntity(ReorderWorkflowSettingsModel model) {
    return ReorderWorkflowSettings(
      autoReorderEnabled: model.autoReorderEnabled,
      reorderPointMultiplier: model.reorderPointMultiplier,
      maxPendingOrders: model.maxPendingOrders,
    );
  }

  static ReorderWorkflowSettingsModel fromEntity(
      ReorderWorkflowSettings entity) {
    return ReorderWorkflowSettingsModel(
      autoReorderEnabled: entity.autoReorderEnabled,
      reorderPointMultiplier: entity.reorderPointMultiplier,
      maxPendingOrders: entity.maxPendingOrders,
    );
  }
}
