// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/reorderWorkflowSettingsModel.dart';
import 'package:clean_arch_app/domain/entities/reorderWorkflowSettings.dart';

class ReorderWorkflowSettingsMapper {
  static ReorderWorkflowSettings toEntity(ReorderWorkflowSettingsModel model) {
    return ReorderWorkflowSettings(
      autoReorderEnabled: model.autoReorderEnabled,
      reorderPointMultiplier: model.reorderPointMultiplier,
      maxPendingOrders: model.maxPendingOrders,
    );
  }

  static ReorderWorkflowSettingsModel fromEntity(
    ReorderWorkflowSettings entity,
  ) {
    return ReorderWorkflowSettingsModel(
      autoReorderEnabled: entity.autoReorderEnabled,
      reorderPointMultiplier: entity.reorderPointMultiplier,
      maxPendingOrders: entity.maxPendingOrders,
    );
  }
}
