// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:stocktrack_pro/data/models/settings/stock_take_settings_model.dart';
import 'package:stocktrack_pro/domain/entities/settings/stock_take_settings.dart';

class StockTakeSettingsMapper {
  static StockTakeSettings toEntity(StockTakeSettingsModel model) {
    return StockTakeSettings(
      gpsEnforced: model.gpsEnforced,
      maxDistanceMeters: model.maxDistanceMeters,
      allowedLocations: model.allowedLocations,
    );
  }

  static StockTakeSettingsModel fromEntity(StockTakeSettings entity) {
    return StockTakeSettingsModel(
      gpsEnforced: entity.gpsEnforced,
      maxDistanceMeters: entity.maxDistanceMeters,
      allowedLocations: entity.allowedLocations,
    );
  }
}
