// GENERATED BY AMAR SCRIPT – EDIT MODEL

import 'package:clean_arch_app/data/models/settings/supplier_support_settings_model.dart';
import 'package:clean_arch_app/domain/entities/settings/supplier_support_settings.dart';

class SupplierSupportSettingsMapper {
  static SupplierSupportSettings toEntity(SupplierSupportSettingsModel model) {
    return SupplierSupportSettings(
      enabled: model.enabled,
      supplierRoles: model.supplierRoles,
    );
  }

  static SupplierSupportSettingsModel fromEntity(
      SupplierSupportSettings entity) {
    return SupplierSupportSettingsModel(
      enabled: entity.enabled,
      supplierRoles: entity.supplierRoles,
    );
  }
}
