// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:clean_arch_app/data/models/supplierSupportSettingsModel.dart';
import 'package:clean_arch_app/domain/entities/supplierSupportSettings.dart';

class SupplierSupportSettingsMapper {
  static SupplierSupportSettings toEntity(SupplierSupportSettingsModel model) {
    return SupplierSupportSettings(
        enabled: model.enabled,
        supplierRoles: model.supplierRoles?.map((e) => String Mapper.toEntity(
            e)).toList(),);
  }

  static SupplierSupportSettingsModel fromEntity(
      SupplierSupportSettings entity) {
    return SupplierSupportSettingsModel(
        enabled: entity.enabled,
        supplierRoles: entity.supplierRoles?.map((e) => String Mapper.fromEntity
            (e)).toList(),);
  }
}
