// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

import 'bom_item.dart';

class BillOfMaterials extends Equatable {
  final String productId;
  final List<BomItem> components;
  final int yieldPerRun;
  final double scrapPercent;

  const BillOfMaterials({
    required this.productId,
    required this.components,
    required this.yieldPerRun,
    required this.scrapPercent,
  });

  BillOfMaterials copyWith({String? productId, List<
      BomItem>? components, int? yieldPerRun, double? scrapPercent}) {
    return BillOfMaterials(
      productId: productId ?? this.productId,
      components: components ?? this.components,
      yieldPerRun: yieldPerRun ?? this.yieldPerRun,
      scrapPercent: scrapPercent ?? this.scrapPercent,
    );
  }

  @override
  List<Object?> get props => [productId, components, yieldPerRun, scrapPercent];
}
