// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class BomItem extends Equatable {
  final String rawMaterialId;
  final int quantityPerUnit;

  const BomItem({required this.rawMaterialId, required this.quantityPerUnit});

  BomItem copyWith({String? rawMaterialId, int? quantityPerUnit}) {
    return BomItem(
      rawMaterialId: rawMaterialId ?? this.rawMaterialId,
      quantityPerUnit: quantityPerUnit ?? this.quantityPerUnit,
    );
  }

  @override
  List<Object?> get props => [rawMaterialId, quantityPerUnit];
}
