// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Category extends Equatable {
  final String id;
  final String name;
  final String? description;
  final String? parentCategoryId;

  const Category({
    required this.id,
    required this.name,
    this.description,
    this.parentCategoryId,
  });

  Category copyWith(
      {String? id, String? name, String? description, String? parentCategoryId}) {
    return Category(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      parentCategoryId: parentCategoryId ?? this.parentCategoryId,
    );
  }

  @override
  List<Object?> get props => [id, name, description, parentCategoryId];
}
