// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Product extends Equatable {
  final String id;
  final String name;
  final String sku;
  final String? description;
  final String categoryId;
  final String supplierId;
  final double? price;
  final double? costPrice;
  final List<String>? tags;

  const Product({
    required this.id,
    required this.name,
    required this.sku,
    this.description,
    required this.categoryId,
    required this.supplierId,
    this.price,
    this.costPrice,
    this.tags,
  });

  Product copyWith(
      {String? id, String? name, String? sku, String?? description, String? categoryId, String? supplierId, double?? price, double?? costPrice, List<String>?? tags}) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      sku: sku ?? this.sku,
      description: description ?? this.description,
      categoryId: categoryId ?? this.categoryId,
      supplierId: supplierId ?? this.supplierId,
      price: price ?? this.price,
      costPrice: costPrice ?? this.costPrice,
      tags: tags ?? this.tags,
    );
  }

  @override
  List<Object?> get props =>
      [
        id,
        name,
        sku,
        description,
        categoryId,
        supplierId,
        price,
        costPrice,
        tags
      ];
}
