// GENERATED BY AMAR SCRIPT – EDIT MODEL
import 'package:equatable/equatable.dart';

class Supplier extends Equatable {
  final String id;
  final String name;

  const Supplier({required this.id, required this.name});

  Supplier copyWith({String? id, String? name}) {
    return Supplier(id: id ?? this.id, name: name ?? this.name);
  }

  @override
  List<Object?> get props => [id, name];
}
